[theme]
base = "light"
primaryColor = "#e7474e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f6f8"
textColor = "#242933"
font = "sans serif"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
