[theme]
base = "dark"
primaryColor = "#d83f4c"
backgroundColor = "#111318"
secondaryBackgroundColor = "#181c23"
textColor = "#d6d8df"
font = "sans serif"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
